A notebook showing how to join cell_metadata and cell-by-gene data with CCF annotations

In [1]:
import abc_atlas_access.abc_atlas_cache.abc_project_cache as abc_project_cache

In [2]:
import numpy as np
import os
import pandas as pd

cache_dir = "/Volumes/mazarbul/workspace/abc_cache"

if not os.path.isdir(cache_dir):
    raise RuntimeError(
        f"{cache_dir} is not a valid directory in your system\n"
        "Set cache_dir above to the path to the directory where you want to download ABC Atlas data"
    )

abc_cache = abc_project_cache.AbcProjectCache.from_cache_dir(cache_dir)

In [3]:
abc_cache.load_latest_manifest()

In [4]:
abc_cache.list_directories

['ASAP-PMDBS-10X',
 'ASAP-PMDBS-taxonomy',
 'Allen-CCF-2020',
 'Consensus-WMB-AIBS-10X',
 'Consensus-WMB-Macosko-10X',
 'Consensus-WMB-integrated-taxonomy',
 'HMBA-10xMultiome-BG',
 'HMBA-10xMultiome-BG-Aligned',
 'HMBA-BG-taxonomy-CCN20250428',
 'HMBA-MERSCOPE-H22.30.001-BG',
 'HMBA-MERSCOPE-QM23.50.001-BG',
 'HMBA-Xenium-CJ23.56.004-BG',
 'MERFISH-C57BL6J-638850',
 'MERFISH-C57BL6J-638850-CCF',
 'MERFISH-C57BL6J-638850-imputed',
 'MERFISH-C57BL6J-638850-sections',
 'SEAAD-taxonomy',
 'WHB-10Xv3',
 'WHB-taxonomy',
 'WMB-10X',
 'WMB-10XMulti',
 'WMB-10Xv2',
 'WMB-10Xv3',
 'WMB-neighborhoods',
 'WMB-taxonomy',
 'Zeng-Aging-Mouse-10Xv3',
 'Zeng-Aging-Mouse-WMB-taxonomy',
 'Zhuang-ABCA-1',
 'Zhuang-ABCA-1-CCF',
 'Zhuang-ABCA-2',
 'Zhuang-ABCA-2-CCF',
 'Zhuang-ABCA-3',
 'Zhuang-ABCA-3-CCF',
 'Zhuang-ABCA-4',
 'Zhuang-ABCA-4-CCF',
 'mmc-gene-mapper']

# Get MERFISH cell metadata

In [5]:
merfish_dir = 'MERFISH-C57BL6J-638850'

In [6]:
cell_metadata = abc_cache.get_metadata_dataframe(
    directory=merfish_dir,
    file_name='cell_metadata'
)

In [7]:
cell_metadata

,cell_label,brain_section_label,cluster_alias,average_correlation_score,feature_matrix_label,donor_label,donor_genotype,donor_sex,x,y,z,abc_sample_id
0,1019171907102340387-1,C57BL6J-638850.37,1408,0.596276,C57BL6J-638850,C57BL6J-638850,wt/wt,M,7.226245,4.148963,6.6,c9881423-76a7-4835-ba8b-7942fd384b6b
1,1104095349101460194-1,C57BL6J-638850.26,4218,0.641180,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.064889,7.309543,4.2,aa815488-6487-4e47-8a5e-d82ac9933bc6
2,1017092617101450577,C57BL6J-638850.25,4218,0.763531,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.792921,8.189973,4.0,91ef7a85-8e3e-4410-8ee2-785788df3ebe
3,1018093344101130233,C57BL6J-638850.13,4218,0.558073,C57BL6J-638850,C57BL6J-638850,wt/wt,M,3.195950,5.868655,2.4,18991e17-fbd3-4ba0-9c60-1281f56ac520
4,1019171912201610094,C57BL6J-638850.27,4218,0.591009,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.635732,7.995842,4.4,5e155936-e40d-4c6b-8971-e7fb0079274b
...,...,...,...,...,...,...,...,...,...,...,...,...
3938803,1018093344100380167-3,C57BL6J-638850.47,5252,0.574988,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.560003,4.669243,8.8,73bc8aed-8a4a-428d-8d75-c37d41766370
3938804,1017165415100930567,C57BL6J-638850.57,5254,0.620546,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.032556,3.695696,11.0,a137c81a-b2b8-4c85-b967-3ec5753e6833
3938805,1017155956102610748,C57BL6J-638850.49,5254,0.548053,C57BL6J-638850,C57BL6J-638850,wt/wt,M,2.549142,4.231188,9.2,4322a30f-c4c4-4f7a-a915-40037c62eaa6
3938806,1017155956101980080-1,C57BL6J-638850.50,5252,0.621901,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.381324,5.784595,9.4,b2c01bcb-5f98-4247-bb74-1ca4667220b5
3938807,1018093344102220578-3,C57BL6J-638850.36,5252,0.625139,C57BL6J-638850,C57BL6J-638850,wt/wt,M,6.184499,6.654317,6.4,be0a63d6-7927-414c-a486-ebbf1e722b0b

# Get MERFISH CCF coords

In [8]:
merfish_ccf_dir = 'MERFISH-C57BL6J-638850-CCF'

In [9]:
abc_cache.list_metadata_files(directory=merfish_ccf_dir)

['ccf_coordinates',
 'cell_metadata_with_parcellation_annotation',
 'reconstructed_coordinates']

In [10]:
cell_ccf_coordinates = abc_cache.get_metadata_dataframe(
    directory=merfish_ccf_dir,
    file_name='ccf_coordinates'
)

/Users/scott.daniel/miniconda3/envs/webinar_2026_02/lib/python3.12/site-packages/abc_atlas_access/abc_atlas_cache/abc_project_cache.py:643: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(path, **kwargs)

In [11]:
cell_ccf_coordinates

,cell_label,x,y,z,parcellation_index
0,1019171911101460569,12.282330,6.987808,7.385773,945
1,1019171911101550321,12.192214,7.002155,4.366855,945
2,1019171911100841066,12.500341,4.750392,7.074634,893
3,1019171911101400425,12.231647,6.544816,4.128568,842
4,1019171911101380264,12.238502,6.135836,2.948194,0
...,...,...,...,...,...
3739956,1017201423100590639,0.244132,5.446741,5.165418,1005
3739957,1017201423100550444,0.446877,3.450430,5.167952,213
3739958,1017201423100460203-1,0.478625,3.244104,5.535724,497
3739959,1017201423100380114-1,0.429646,3.922535,6.213221,213
3739960,1017201423100540125,0.496993,2.933842,5.088633,688

# Join cell_metadata with ccf_coordinates

In [12]:
cell_metadata.columns

Index(['cell_label', 'brain_section_label', 'cluster_alias',
       'average_correlation_score', 'feature_matrix_label', 'donor_label',
       'donor_genotype', 'donor_sex', 'x', 'y', 'z', 'abc_sample_id'],
      dtype='object')

In [13]:
cell_ccf_coordinates.columns

Index(['cell_label', 'x', 'y', 'z', 'parcellation_index'], dtype='object')

In [14]:
cell_ccf_coordinates.rename(
    {'x': 'x_ccf',
     'y': 'y_ccf',
     'z': 'z_ccf'},
    axis=1,
    inplace=True
)

In [15]:
cell_ccf_coordinates.columns

Index(['cell_label', 'x_ccf', 'y_ccf', 'z_ccf', 'parcellation_index'], dtype='object')

In [16]:
cell_metadata = cell_metadata.join(
    cell_ccf_coordinates.set_index('cell_label'),
    on='cell_label'
)

In [17]:
cell_metadata = cell_metadata.dropna()

In [18]:
cell_metadata.columns

Index(['cell_label', 'brain_section_label', 'cluster_alias',
       'average_correlation_score', 'feature_matrix_label', 'donor_label',
       'donor_genotype', 'donor_sex', 'x', 'y', 'z', 'abc_sample_id', 'x_ccf',
       'y_ccf', 'z_ccf', 'parcellation_index'],
      dtype='object')

In [19]:
len(cell_metadata)

3477817

# Download CCF

In [20]:
ccf_dir = 'Allen-CCF-2020'

In [21]:
abc_cache.list_metadata_files(directory=ccf_dir)

['parcellation',
 'parcellation_term',
 'parcellation_term_set',
 'parcellation_term_set_membership',
 'parcellation_term_with_counts',
 'parcellation_to_parcellation_term_membership',
 'parcellation_to_parcellation_term_membership_acronym',
 'parcellation_to_parcellation_term_membership_blue',
 'parcellation_to_parcellation_term_membership_color',
 'parcellation_to_parcellation_term_membership_green',
 'parcellation_to_parcellation_term_membership_name',
 'parcellation_to_parcellation_term_membership_red']

In [22]:
parcellation_term_set = abc_cache.get_metadata_dataframe(
    directory=ccf_dir,
    file_name='parcellation_term_set'
)

In [23]:
parcellation_term_set

,label,description,name,parcellation_terminology_label,term_set_order,parent_term_set_label
0,AllenCCF-Ontology-2017-ORGA,organ,organ,AllenCCF-Ontology-2017,0,NaN
1,AllenCCF-Ontology-2017-CATE,mouse brain anatomical catergories,category,AllenCCF-Ontology-2017,1,AllenCCF-Ontology-2017-ORGA
2,AllenCCF-Ontology-2017-DIVI,mouse brain divisions,division,AllenCCF-Ontology-2017,2,AllenCCF-Ontology-2017-CATE
3,AllenCCF-Ontology-2017-STRU,mouse brain structures,structure,AllenCCF-Ontology-2017,3,AllenCCF-Ontology-2017-DIVI
4,AllenCCF-Ontology-2017-SUBS,mouse brain substructures,substructure,AllenCCF-Ontology-2017,4,AllenCCF-Ontology-2017-STRU

In [24]:
membership = abc_cache.get_metadata_dataframe(
    directory=ccf_dir,
    file_name='parcellation_to_parcellation_term_membership'
)

In [25]:
membership

,parcellation_label,parcellation_term_label,parcellation_term_set_label,parcellation_index,voxel_count,volume_mm3,color_hex_triplet,red,green,blue,parcellation_term_name,parcellation_term_acronym,parcellation_term_set_name,term_set_order,term_order,parent_term_label
0,AllenCCF-Annotation-2020-997,AllenCCF-Ontology-2017-997,AllenCCF-Ontology-2017-ORGA,987,3564320,3.564320,#FFFFFF,255,255,255,brain,brain,organ,0,0,NaN
1,AllenCCF-Annotation-2020-68,AllenCCF-Ontology-2017-997,AllenCCF-Ontology-2017-ORGA,63,256520,0.256520,#FFFFFF,255,255,255,brain,brain,organ,0,0,NaN
2,AllenCCF-Annotation-2020-68,AllenCCF-Ontology-2017-8,AllenCCF-Ontology-2017-CATE,63,256520,0.256520,#BFDAE3,191,218,227,Basic cell groups and regions,grey,category,1,1,AllenCCF-Ontology-2017-997
3,AllenCCF-Annotation-2020-68,AllenCCF-Ontology-2017-315,AllenCCF-Ontology-2017-DIVI,63,256520,0.256520,#70FF71,112,255,113,Isocortex,Isocortex,division,2,1,AllenCCF-Ontology-2017-8
4,AllenCCF-Annotation-2020-68,AllenCCF-Ontology-2017-184,AllenCCF-Ontology-2017-STRU,63,256520,0.256520,#268F45,38,143,69,"Frontal pole, cerebral cortex",FRP,structure,3,1,AllenCCF-Ontology-2017-315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3435,AllenCCF-Annotation-2020-145,ABC-Ontology-2023-V4-structure,AllenCCF-Ontology-2017-STRU,140,499566,0.499566,#AAAAAA,170,170,170,"fourth ventricle, unassigned",V4-unassigned,structure,3,367,AllenCCF-Ontology-2017-145
3436,AllenCCF-Annotation-2020-145,ABC-Ontology-2023-V4-substructure,AllenCCF-Ontology-2017-SUBS,140,499566,0.499566,#AAAAAA,170,170,170,"fourth ventricle, unassigned",V4-unassigned,substructure,4,885,ABC-Ontology-2023-V4-structure
3437,AllenCCF-Annotation-2020-153,ABC-Ontology-2023-V4r-substructure,AllenCCF-Ontology-2017-SUBS,148,461680,0.461680,#AAAAAA,170,170,170,lateral recess,V4r,substructure,4,886,AllenCCF-Ontology-2017-153
3438,AllenCCF-Annotation-2020-164,ABC-Ontology-2023-c-structure,AllenCCF-Ontology-2017-STRU,159,432,0.000432,#AAAAAA,170,170,170,"central canal, spinal cord/medulla",c,structure,3,369,AllenCCF-Ontology-2017-164
3439,AllenCCF-Annotation-2020-164,ABC-Ontology-2023-c-substructure,AllenCCF-Ontology-2017-SUBS,159,432,0.000432,#AAAAAA,170,170,170,"central canal, spinal cord/medulla",c,substructure,4,887,ABC-Ontology-2023-c-structure

In [26]:
for term_set_label in membership.parcellation_term_set_label.unique():
    subset = membership[membership.parcellation_term_set_label == term_set_label]
    term_set_name = subset.parcellation_term_set_name.iloc[0]
    subset = subset[['parcellation_index', 'parcellation_term_name', 'parcellation_term_acronym']]
    subset = subset.rename(
        {'parcellation_term_name': f'{term_set_name}_name',
         'parcellation_term_acronym': f'{term_set_name}_acronym'},
        axis=1
    )
    cell_metadata = cell_metadata.join(
        subset.set_index('parcellation_index'),
        on='parcellation_index'
    )
    print(f"joined '{term_set_name}'")

joined 'organ'
joined 'category'
joined 'division'
joined 'structure'
joined 'substructure'

In [27]:
cell_metadata

,cell_label,brain_section_label,cluster_alias,average_correlation_score,feature_matrix_label,donor_label,donor_genotype,donor_sex,x,y,...,organ_name,organ_acronym,category_name,category_acronym,division_name,division_acronym,structure_name,structure_acronym,substructure_name,substructure_acronym
0,1019171907102340387-1,C57BL6J-638850.37,1408,0.596276,C57BL6J-638850,C57BL6J-638850,wt/wt,M,7.226245,4.148963,...,brain,brain,Basic cell groups and regions,grey,Hippocampal formation,HPF,Dentate gyrus,DG,"Dentate gyrus, polymorph layer",DG-po
1,1104095349101460194-1,C57BL6J-638850.26,4218,0.641180,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.064889,7.309543,...,brain,brain,Basic cell groups and regions,grey,Pons,P,Tegmental reticular nucleus,TRN,Tegmental reticular nucleus,TRN
2,1017092617101450577,C57BL6J-638850.25,4218,0.763531,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.792921,8.189973,...,brain,brain,Basic cell groups and regions,grey,Pons,P,"Pons, unassigned",P-unassigned,"Pons, unassigned",P-unassigned
3,1018093344101130233,C57BL6J-638850.13,4218,0.558073,C57BL6J-638850,C57BL6J-638850,wt/wt,M,3.195950,5.868655,...,brain,brain,fiber tracts,fiber tracts,cerebellum related fiber tracts,cbf,arbor vitae,arb,arbor vitae,arb
4,1019171912201610094,C57BL6J-638850.27,4218,0.591009,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.635732,7.995842,...,brain,brain,Basic cell groups and regions,grey,Pons,P,"Pons, unassigned",P-unassigned,"Pons, unassigned",P-unassigned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3938803,1018093344100380167-3,C57BL6J-638850.47,5252,0.574988,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.560003,4.669243,...,brain,brain,Basic cell groups and regions,grey,Isocortex,Isocortex,"Primary somatosensory area, nose",SSp-n,"Primary somatosensory area, nose, layer 2/3",SSp-n2/3
3938804,1017165415100930567,C57BL6J-638850.57,5254,0.620546,C57BL6J-638850,C57BL6J-638850,wt/wt,M,5.032556,3.695696,...,brain,brain,Basic cell groups and regions,grey,Isocortex,Isocortex,"Anterior cingulate area, dorsal part",ACAd,"Anterior cingulate area, dorsal part, layer 5",ACAd5
3938805,1017155956102610748,C57BL6J-638850.49,5254,0.548053,C57BL6J-638850,C57BL6J-638850,wt/wt,M,2.549142,4.231188,...,brain,brain,Basic cell groups and regions,grey,Isocortex,Isocortex,"Primary somatosensory area, mouth",SSp-m,"Primary somatosensory area, mouth, layer 6a",SSp-m6a
3938806,1017155956101980080-1,C57BL6J-638850.50,5252,0.621901,C57BL6J-638850,C57BL6J-638850,wt/wt,M,1.381324,5.784595,...,brain,brain,Basic cell groups and regions,grey,Isocortex,Isocortex,Supplemental somatosensory area,SSs,"Supplemental somatosensory area, layer 1",SSs1
3938807,1018093344102220578-3,C57BL6J-638850.36,5252,0.625139,C57BL6J-638850,C57BL6J-638850,wt/wt,M,6.184499,6.654317,...,brain,brain,Basic cell groups and regions,grey,Hypothalamus,HY,"Hypothalamus, unassigned",HY-unassigned,"Hypothalamus, unassigned",HY-unassigned

# Compare CA1 and CA3

In [28]:
ca1 = cell_metadata[cell_metadata.structure_acronym=='CA1']

In [29]:
ca3 = cell_metadata[cell_metadata.structure_acronym=='CA3']

In [30]:
import anndata

In [31]:
abc_cache.list_expression_matrix_files(directory=merfish_dir)

['C57BL6J-638850/log2', 'C57BL6J-638850/raw']

In [32]:
merfish_expression_path = abc_cache.get_data_path(
    directory=merfish_dir,
    file_name='C57BL6J-638850/log2'
)

In [33]:
merfish_expression = anndata.read_h5ad(
    merfish_expression_path,
    backed='r'
)

In [34]:
merfish_expression

AnnData object with n_obs × n_vars = 4334174 × 550 backed at '/Volumes/mazarbul/workspace/abc_cache/expression_matrices/MERFISH-C57BL6J-638850/20230830/C57BL6J-638850-log2.h5ad'
    obs: 'brain_section_label'
    var: 'gene_symbol', 'transcript_identifier'
    uns: 'accessed_on', 'src'

In [35]:
ca1_data = merfish_expression[merfish_expression.obs.index.isin(ca1.cell_label)].to_memory()

In [36]:
ca3_data = merfish_expression[merfish_expression.obs.index.isin(ca3.cell_label)].to_memory()

In [37]:
len(ca1_data)

56385

In [38]:
len(ca3_data)

47101

In [39]:
import scipy.stats

In [40]:
wilcoxon = scipy.stats.ranksums(ca1_data.X.toarray(), ca3_data.X.toarray(), axis=0)

In [41]:
delta = (ca1_data.X.mean(axis=0)-ca3_data.X.mean(axis=0))

In [42]:
delta.shape

(1, 550)

In [43]:
delta = np.array(delta).flatten()

In [44]:
delta.shape

(550,)

In [45]:
delta.max()

np.float64(2.43085232647394)

In [46]:
valid = np.logical_and(
    wilcoxon.pvalue<0.01,
    delta>1.0
)

In [47]:
valid_idx = np.where(valid)

In [48]:
valid_idx

(array([138, 168, 441]),)

In [49]:
delta[valid_idx]

array([1.81804315, 2.43085233, 1.47975645])

In [50]:
ca1_data.var.iloc[valid_idx[0]]

                   gene_symbol transcript_identifier
gene_identifier
ENSMUSG00000026841      Fibcd1    ENSMUST00000028188
ENSMUSG00000037362        Ccn3    ENSMUST00000050027
ENSMUSG00000090125      Pou3f1    ENSMUST00000053491

In [51]:
wilcoxon.pvalue[valid_idx]

array([0., 0., 0.])